export const SET_LOADING='SET_LOADING';
export const SET_ISLOGED='SET_ISLOGED';
export const SET_USER='SET_USER';
export const SET_RECIEPT='SET_RECIEPT';
export const SET_STUDENT_RESULT='SET_STUDENT_RESULT';